language: cpp
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind
      - autotools-dev
      - automake
env:
  - MAKEFLAG="CHECK=1"
  - MAKEFLAG="CHECK=0"



install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; export CC=gcc-4.8; fi
  - git clone --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./autogen.sh && ./configure && make && make bootstrap-pkg-minimal)
  - ( cd gap/pkg && git clone --depth=2 https://github.com/gap-packages/io && cd io && ./autogen.sh && ./configure && make )
  - ( cd gap/pkg && wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/atlasrep1r5p0.tar.bz2 && tar -xf atlasrep1r5p0.tar.bz2 )
  - pwd
  - ( ./autogen.sh && ./configure --with-gaproot=gap && make )
  - pwd
  - ls
  - ls gap
  - ls gap/pkg
  - echo ln -s $(pwd) gap/pkg/ferret
  - ln -s $(pwd) gap/pkg/ferret
  - cat ferret.vars

script:
  - scripts/quick_test.sh ${MAKEFLAG}
