language: cpp

before_install:
  - sudo add-apt-repository ppa:mhorn/gap -y
  - sudo apt-get update -y
  - sudo apt-get install gap-for-opt libgmp3-dev parallel -y

install:
  - ./configure /opt/gap && make

script:
  - scripts/quick_test.sh

