language: generic
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ubuntu-toolchain-precise-3.8
    packages:
      - gcc-5
      - g++-5
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind
      - autotools-dev
      - automake
env:
  - BRANCH="master" CONF_FLAG="" CXX="g++-5" CC="gcc-5"
  - BRANCH="stable-4.8" CONF_FLAG="" CXX="g++-5" CC="gcc-5"
  - BRANCH="stable-4.9" CONF_FLAG="" CXX="g++-5" CC="gcc-5"
#  - BRANCH="hpcgap-default" CONF_FLAG="--enable-checking"
  - BRANCH="master" CONF_FLAG="--enable-checking" CXX="g++-5" CC="gcc-5"
  - BRANCH="master" CONF_FLAG="--enable-timing" CXX="g++-5" CC="gcc-5"
  - BRANCH="master" CONF_FLAG="--enable-checking --enable-timing" CXX="g++-5" CC="gcc-5"
  


install:
  - echo $BRANCH ":" $CONF_FLAG
  - echo $CXX ":" $CC
  - git clone -b $BRANCH --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./autogen.sh || echo no autogen )
  - ( cd gap && ./configure && make && make bootstrap-pkg-minimal V=1)
  - ( cd gap/pkg && git clone --depth=2 https://github.com/gap-packages/io && cd io && ./autogen.sh && ./configure && make )
  - ( cd gap/pkg && wget http://www.gap-system.org/pub/gap/gap48/tar.bz2/packages/atlasrep1r5p0.tar.bz2 && tar -xf atlasrep1r5p0.tar.bz2 )
  - pwd
  - echo ln -s $(pwd) gap/pkg/ferret
  - ln -s $(pwd) gap/pkg/ferret
  - ( cd gap/pkg/ferret && ./autogen.sh && ./configure $CONF_FLAG && make V=1)
  - pwd
  - ls
  - ls gap
  - ls gap/pkg
  - cat ferret.vars

script:
  - (cd gap/pkg/ferret && scripts/quick_test.sh ${MAKEFLAG})
