language: cpp

branches:
  except:
    - gh-pages
    
env:
  - MAKEFLAG="CHECK=1"
  - MAKEFLAG="CHECK=0"

before_install:
  - sudo add-apt-repository ppa:azumanga/gap -y
  - sudo apt-get update -y
  - sudo apt-get install gap-snapshot libgmp3-dev parallel valgrind -y


install:
  - ./configure /opt/gap && make
  - mkdir gap-root && mkdir gap-root/pkg && ln -s $(pwd) gap-root/pkg/ferret
  - echo 'export GAPEXEC="$GAPEXEC -l '$(pwd)'/gap-root;"' >> ferret.vars
  - cat ferret.vars

script:
  - scripts/quick_test.sh ${MAKEFLAG}

